Fixed Typescript type error
src/spec/spec.ts:24:5 - error TS2322: Type 'Promise<Object>' is not assignable to type 'Promise<ApiSpec>'.
  Type 'Object' is not assignable to type 'ApiSpec'.
    The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
      Property 'host' is missing in type 'Object'